apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.cert is required" .Values.tls.cert }}
  tls.key: {{ required "tls.key is required" .Values.tls.key }}
