apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "webhook.selectorLabels" . | nindent 4 }}
